plot:
  _target_: diffract.viz.plots.base.UpdateFigure
  layout:
    width: 1000
    height: 480
  yaxes:
    title: "count per bin (mean over heads)"
    type: log
    dtick: 1
  plot:
    _target_: diffract.viz.plots.cluster.ClusterBarChart
    field: weights_svals
    title: "Singular value spectrum: 16k vs 128k pre-train steps"
    parameter_names:
      - re:.*(q|k|v|o)_proj_head.*

    group_by: [model_id]
    aggregate_by: null
    color_by: model_id
    dash_by: model_id
    legend_format: "{model_id}"

    num_bins: 40
    left_bound: 0.0
    binning: linear
    draw_statistics: false
