"""Model management namespace for Session."""

from __future__ import annotations

import logging
from collections.abc import Callable
from dataclasses import replace
from typing import TYPE_CHECKING, Any

from dependency_injector.wiring import Provide, inject

from diffract.core.constants import TABLE_AGGREGATES, TABLE_PARAMETERS
from diffract.core.data.nn.extractors.base import ExtractorOverrides, ParameterOverrides
from diffract.core.utils.exceptions import format_exception_message
from diffract.session.errors import (
    ModelAlreadyExistsError,
    ModelNotFoundError,
    SessionError,
)
from diffract.session.session import Session, SessionContext

from .parameters import ParametersNamespace

if TYPE_CHECKING:
    from collections.abc import Iterable

    from diffract.core.data.nn.aggregates.repository import AggregateRepository
    from diffract.core.data.nn.extractors.handlers.base import ParameterHandler
    from diffract.core.data.nn.extractors.interface import IParameterExtractor
    from diffract.core.data.nn.params.interface import IParameterRepository


logger = logging.getLogger(__name__)

__all__ = [
    "ModelsNamespace",
    "ParametersNamespace",
]


class ModelsNamespace:
    """Model management API."""

    @inject
    def __init__(
        self,
        session_or_context: Session | SessionContext,
        parameter_repository: IParameterRepository = Provide["nn.parameter_repository"],
        aggregate_repository: AggregateRepository = Provide["nn.aggregate_repository"],
        extractor_factory: Callable[..., IParameterExtractor] = Provide[
            "nn.extractor_factory.provider"
        ],
    ) -> None:
        self.__session_or_context = session_or_context
        self.__param_repo = parameter_repository
        self.__agg_repo = aggregate_repository
        self.__extractor_factory = extractor_factory

        self.parameters = ParametersNamespace(session_or_context)

    def add(
        self,
        model: Any,
        model_id: str | None = None,
        parameter_overrides: dict[str, ParameterOverrides] | None = None,
        custom_handlers: Iterable[ParameterHandler] | None = None,
    ) -> None:
        """Add a neural network model to the session.

        Extracts parameters from the provided model and stores them for analysis.
        Parameters are automatically persisted and can be retrieved in future sessions.

        Args:
            model: Neural network model object (PyTorch, TensorFlow, etc.)
                or a dict mapping parameter names to NumPy arrays.
            model_id: Unique identifier for the model. Auto-generated if None.
            parameter_overrides: Custom parameter extraction overrides by name.
            custom_handlers: Additional parameter handlers for custom parameter types.

        Raises:
            ModelAlreadyExistsError: If model_id already exists in the session.
            SessionError: If parameter extraction fails or yields no parameters.
        """
        with self.__session_or_context:
            try:
                extractor = self.__extractor_factory(
                    model=model,
                    overrides=self.__build_extractor_overrides(
                        model_id, parameter_overrides
                    ),
                    custom_handlers=custom_handlers,
                )

                previous_len = len(self.__param_repo)
                extractor.extract_parameters(self.__param_repo)
                new_len = len(self.__param_repo)

                self.__session_or_context._field_cache.invalidate()

            except SessionError:
                raise
            except Exception as e:
                msg = f"Failed to add model: {format_exception_message(e)}"
                raise SessionError(msg) from e

            if new_len == previous_len:
                msg = (
                    f"Model '{model_id or type(model).__name__}' produced no "
                    "parameters. Unsupported parameter types are skipped during "
                    "extraction; supported inputs are PyTorch, TensorFlow, "
                    "Flax, and ONNX models (install the matching extra) and "
                    "dicts of 2D floating-point NumPy arrays."
                )
                raise SessionError(msg)

            logger.info(
                "Added model '%s' with %d parameters",
                model_id or "<auto-generated>",
                new_len - previous_len,
            )

    def rename(
        self,
        model_id: str,
        new_model_id: str,
    ) -> None:
        """Rename a model in the session.

        Args:
            model_id: ID of the model to rename.
            new_model_id: New ID for the model.

        Raises:
            ModelNotFoundError: If model_id does not exist.
            ModelAlreadyExistsError: If new_model_id already exists.
        """
        with self.__session_or_context:
            params = self.__param_repo.create_view()
            model_params = params.filter_by_model_id(model_id)

            if not model_params:
                msg = f"Model '{model_id}' not found"
                raise ModelNotFoundError(msg)

            new_model_params = params.filter_by_model_id(new_model_id)
            if new_model_params:
                msg = f"Model '{new_model_id}' already exists"
                raise ModelAlreadyExistsError(msg)

            param_uids = model_params.list_uids()

            aggs = self.__agg_repo.create_view()
            model_aggs = aggs.filter_by_context_models(model_id)
            agg_uids = model_aggs.list_uids()

            with self.__param_repo:
                for uid in param_uids:
                    param = params[uid]
                    old_meta = param.meta
                    new_meta = replace(old_meta, model_id=new_model_id)

                    object.__setattr__(param, "meta", new_meta)

                    meta_dict = new_meta.to_dict()
                    meta_dict.pop("uid")
                    self.__param_repo.metadata_index.upsert(
                        TABLE_PARAMETERS,
                        uid=uid,
                        **meta_dict,
                    )

            with self.__agg_repo:
                for uid in agg_uids:
                    agg = aggs[uid]
                    old_meta = agg.meta
                    new_context_models = tuple(
                        new_model_id if cm == model_id else cm
                        for cm in old_meta.context_models
                    )
                    new_meta = replace(old_meta, context_models=new_context_models)

                    object.__setattr__(agg, "meta", new_meta)

                    meta_dict = new_meta.to_dict()
                    meta_dict.pop("uid")
                    self.__agg_repo.metadata_index.upsert(
                        TABLE_AGGREGATES,
                        uid=uid,
                        **meta_dict,
                    )

            self.__session_or_context._field_cache.invalidate()

            logger.info("Renamed model '%s' to '%s'", model_id, new_model_id)

    def erase(
        self,
        *model_ids: str,
        erase_all: bool = False,
    ) -> None:
        """Erase all parameters and results for specified models.

        Removes model parameters from both memory and persistent storage.
        Use with caution as this operation cannot be undone.

        Args:
            *model_ids: Model IDs to erase. Required if erase_all is False.
            erase_all: If True, erases all models. model_ids must be empty.

        Raises:
            ValueError: If neither model_ids nor erase_all is specified,
                or if both are specified.
            ModelNotFoundError: If any specified model ID is not found.
        """
        with self.__session_or_context:
            if (not model_ids) ^ erase_all:
                if not model_ids:
                    msg = "No model_ids provided and erase_all=False"
                else:
                    msg = "Cannot specify both model_ids and erase_all=True"
                raise ValueError(msg)

            if erase_all:
                model_ids = tuple(self.list())

            params = self.__param_repo.create_view()
            aggs = self.__agg_repo.create_view()

            erased_uids: list[str] = []
            for model_id in model_ids:
                model_params = params.filter_by_model_id(model_id)

                if not model_params:
                    msg = f"Model '{model_id}' not found"
                    raise ModelNotFoundError(msg)

                model_aggs = aggs.filter_by_context_models(model_id)

                erased_uids.extend(model_params.list_uids())
                model_params.clear(erase=True)
                if model_aggs:
                    model_aggs.clear(erase=True)

                logger.info("Erased model '%s'", model_id)

            self.__session_or_context._field_cache.remove_uids(erased_uids)

    def list(self) -> list[str]:
        """List all model IDs currently in the session.

        Returns:
            Sorted list of unique model IDs present in the session.
        """
        with self.__session_or_context:
            if isinstance(self.__session_or_context, Session):
                params = self.__param_repo.create_view()
            else:
                params = self.__session_or_context._param_filter_context
            model_ids = {param.meta.model_id for param in params}
            return sorted(model_ids)

    def __build_extractor_overrides(
        self,
        model_id: str | None,
        parameter_overrides: dict[str, ParameterOverrides] | None,
    ) -> ExtractorOverrides:
        extractor_overrides_kwargs: dict[str, Any] = {}

        if model_id:
            params = self.__param_repo.create_view()
            model_params = params.filter_by_model_id(model_id)

            if model_params:
                msg = f"Model with uid {model_id} already exists"
                raise ModelAlreadyExistsError(msg)

            extractor_overrides_kwargs["model_id"] = model_id

        if parameter_overrides:
            extractor_overrides_kwargs["parameter_overrides"] = parameter_overrides

        return ExtractorOverrides(**extractor_overrides_kwargs)
