"""Core module for diffract."""

from diffract.core.constants import (
    CONTEXT_SEPARATOR,
    HDF5_INDEX_DATASET,
    HDF5_INDEX_GROUP,
    HDF5_INDEX_TOMBSTONE,
    MODELS_CONTEXT_PREFIX,
    PARAMS_CONTEXT_PREFIX,
    REGEX_PREFIX,
    WEIGHTS_FIELD,
)

__all__ = [
    "CONTEXT_SEPARATOR",
    "HDF5_INDEX_DATASET",
    "HDF5_INDEX_GROUP",
    "HDF5_INDEX_TOMBSTONE",
    "MODELS_CONTEXT_PREFIX",
    "PARAMS_CONTEXT_PREFIX",
    "REGEX_PREFIX",
    "WEIGHTS_FIELD",
]
