plot:
  _target_: diffract.viz.plots.configurer.UpdateFigure
  plot:
    _target_: diffract.viz.plots.scalar.BoxPlot
    field: stable_rank
    title: "stable_rank by model_id"
    group_by: model_id

config:
  layout:
    width: 800
    height: 400
