plot:
  _target_: diffract.viz.plots.base.UpdateFigure
  plot:
    _target_: diffract.viz.plots.boxplot.BoxPlot
    y: stable_rank
    title: "stable_rank by model_id"
    x: model_id

config:
  layout:
    width: 800
    height: 400
