plot:
  _target_: diffract.viz.plots.configurer.UpdateFigure
  plot:
    _target_: diffract.viz.plots.cluster.ClusterBarChart
    field: weights_svals
    title: "Weights singular values"

    # Example: group by model and layer, aggregate across heads
    group_by: [model_id, layer_id, head_id]
    aggregate_by: head_id
    color_by: layer_id
    dash_by: model_id

    num_bins: 18
    binning: exponential
    draw_statistics: true

  layout:
    width: 800
    height: 400
  yaxes:
    title: "count per bin (mean; std below 0)"
